### ISSUE TITLE
Nashorn has been removed for Java 15

### ISSUE THREAD

**Issue by jamierocks** [MinecraftForge/CoreMods#29]
As per [JEP 372 (Remove the Nashorn JavaScript Engine)](http://openjdk.java.net/jeps/372), Nashorn has now been [removed from Java](https://hg.openjdk.java.net/jdk/jdk/rev/9b72cae6d43f).

**Comment by LexManos** [comment]
We know, however Minecraft still targets J8 so that is what we target.
Last time I looked into it, there were external projects ready to go for re-adding JS to the JVM.
So we just need to find one that we can ship IF Mojang ever adopts J15+

**Comment by jamierocks** [comment]
> Last time I looked into it, there were external projects ready to go for re-adding JS to the JVM.

I guess there's always been Mozilla's **[Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Overview)**, though according to the [original JEP](http://openjdk.java.net/jeps/174) to add Nashorn, *"Performance and memory usage of Nashorn applications should be significantly better than Rhino"*.

Oracle seems to be [pushing](https://www.infoworld.com/article/3291322/oracle-switch-now-from-nashorn-javascript-engine-to-graalvm.html) for people to migrate to **[GraalVM](https://www.graalvm.org/)**, so that may well be worth looking into.

**Comment by gigaherz** [comment]
It has been in the back of Lex & CPW's mind for as many years as Nashorn has been deprecated. But so long as the vanilla launcher keeps using java8, there isn't much point changing the code. 

I'd say, and this is my personal opinion: whenever the active LTS version of java (currently java11) starts being distributed without Nashorn, then it will be when it's worth looking into having options for when the platform's installed java isn't enough to run forge. Any platform should at least support the LTS version of Java, and if they don't, that's their issue, not ours.

**Comment by LexManos** [comment]
Ya, Rhino is one of the options I've looked at. It seems like it'd be fine for our use cases, both license and functionality wise. As well as being a respectable download size. GraalVM isn't quite possible as as I said we have to target what Mojang ships. I need to look into it's native compiler to see if it could make the installer native without being 30MB. But that's a different task.

If someone wants to spend some time, feel free to make a POC of switching to Rhino. However it's not a high priority as we're still years away from Mojang even considering shipping J15+

**Comment by kb-1000** [comment]
GraalJS/Truffle are able to be used independent of GraalVM to my knowledge. And it has an option (`polyglot.js.nashorn-compat`) that makes it more Nashorn compatible on the JS side.

**Comment by BedrockLegends** [comment]
Figured to post this here if anyone has not seen this https://mail.openjdk.java.net/pipermail/nashorn-dev/2020-October/007557.html

**Comment by jamierocks** [comment]
The independent Nashorn project has now been released[1], though note that it requires Java 15 to run.

[1] https://mail.openjdk.java.net/pipermail/nashorn-dev/2020-November/007597.html

**Comment by LatvianModder** [comment]
I think it's worth noting that I have a fork of Rhino as a mod to power KubeJS (for the same reason, nashorn dying) here: https://www.curseforge.com/minecraft/mc-mods/rhino which has some improvements over original

**Comment by stevefan1999-personal** [comment]
Maybe we need to consider a short-term transition to Rhino first since Mozilla claims to have added ScriptEngine support in [their latest release](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_13_Release) (as of Jan 2021)

**Comment by TheSilkMiner** [comment]
There's already work being done towards getting Forge to run on Java 15, leveraging an existing Nashorn repack which seems to play nice with Java 14 and lower and doesn't waste that many resources being only 2 MBs in size ([Source: Twitter](https://twitter.com/LexManos/status/1346647814869192704)).

I doubt a transition towards another scripting engine would benefit both the end user and the developers, due to potential compatibility issues between different implementations that could lead to different features being supported.

**Comment by sciwhiz12** [comment]
stevefan:
It is not a workaround to disable the CoreMods system. Forge uses the CoreMods system for runtime patching that would be too maintenance-heavy, such as the `IExtensibleEnum` system.
The draft PR you linked is the envisioned solution in moving towards Java 15 support, but it will still need to be tested extensively and reviewed to ensure that nothing breaks in all situations (since the picture that LexManos posted in that PR does not indicate any mods are installed).
Would you mind joining the [Discord](https://discord.gg/UvedJ9m), so we can continue this conversation there?

**Comment by stevefan1999-personal** [comment]
@sciwhiz12 I haven't really get into the architecture of Forge just yet...while I just made a few learning mods in Kotlin, I had never been touching the Forge main code.

This could take another week to learn the system...

**Comment by LexManos** [comment]
The Nashorn issue has been resolved in https://github.com/MinecraftForge/CoreMods/commit/47918e2f87e920f2c0b5f2d1e0ccc37e335fe484

Any other issues would need to be addressed separately, but I haven't encountered any.
