### ISSUE TITLE
JS Concerns

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/CoreMods#3]
We all know js isn't compiled thus leading to security issues as it could be altered. I prefer compiled mods and I can take a look in the jar and go hey this is a mod and hey I doubt this has been altered in any way. Or hey this jar looks suspicious because it has classes that don't look like a minecraft mod.

The next major concern I am going to adress is does the js even support file input streams? I need it to repalace method instructions for methods that simply don't work. I get the input stream create a class node and get a method node then port over the instructions to the original class node thus overriding it and patching any instructions/local variables. The alternative would be inject an if statement around all instructions and then manually inject the bytecode line by line which is way slower process for a computer to do *and alot more mistakes will likely to happen making the mod unstable*

Another thing is custom class writers. Most people using asm experience class not found exceptions being thrown only in compiled enviorment and the only way to fix it is to make a custom class writer and override the getsuper class. This is fixed with this class found here but, it needs to be a custom class writer. https://github.com/squeek502/ASMHelper/tree/1.10.x/raw/squeek/asmhelper

also I heard lex wanted signed jars which is even more secure. I think js is two steps downhill in security I hope this leans your decision  away from it.

**Comment by LexManos** [comment]
Your initial premise, that because JS is not pre-compiled, it is less secure then precompiled binary classes. Is just flat out the stupidest thing I have EVER heard.
Now skipping that, and going on to what APIs will be exposed to JS. Whatever Java exposes to JS by default, and then the ASM library, will be the core of the APIs exposed. There may be some additions once things are finalized and we work out what things modders want. 
As for signing, you can sign ANYTHING that is in your jar file. Including text/js files. So... just sign your things and move on with your life.
